### ISSUE TITLE
Easy provide of gist-id when required

### ISSUE THREAD

**Issue by groupsky** [Hackafe/atom-sync-settings#103]
When a backup/restore or check for updated backup #88  is called and gist-id is missing, an error is displayed, but then user has to navigate to settings, packages, find the sync-settings package and after that he/she is able to provide the missing value.

Possible solutions are atom/settings-view#436 or #100

**Comment by dirk-thomas** [comment]
PR #140 implemented the described functionality. When mandatory information are missing the error message contains a link which gets you directly to the package settings.

With this and #100 pending I think this ticket can be closed.
