### ISSUE TITLE
What is a valid string path for the Extra Files field?

### ISSUE THREAD

**Issue by akappel** [Hackafe/atom-sync-settings#109]
Hello,

I would like to add my vim-mode keymap configuration file to the list of extra files, but I'm unsure of the syntax. I'm using a Windows machine. I've tried fully qualified names e.g. C:\...\packages\vim-mode\keymaps.cson,  as well as relative paths. I've also tried them with and without single quote marks. Thank you.

P.S. May be good to document this in the wiki once an answer is verified.

**Comment by jerone** [comment]
Right now it only takes files from the root Atom directory (`~/.Atom`). 

When #97 is released, you are free to backup from any directory.

I hope that answers your question.

**Comment by akappel** [comment]
Okay thank you.
