### ISSUE TITLE
Uncaught Error: OAuth2 authentication requires a token or key 

### ISSUE THREAD

**Issue by ltdat287** [Hackafe/atom-sync-settings#112]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.5.0

### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by jerone** [comment]
Duplicate: https://github.com/Hackafe/atom-sync-settings/issues/111
