### ISSUE TITLE
Notification link broken on latest Atom (1.0.7)

### ISSUE THREAD

**Issue by eduardot42** [Hackafe/atom-sync-settings#120]
Running a sync backup on 2 different machines (both running Mac OS X), the notification that pops up after it successfully uploads displays the link as follows:

![screenshot 2015-08-13 17 37 18 2](https://cloud.githubusercontent.com/assets/8451602/9262374/82efd70a-41e2-11e5-8169-f64f1c1b4e16.png)

Whereas before it would properly create a usable link. Not a big deal, as you can just use the shift+cmd+P and use the option to view backup, more of a heads up that on latest atom it displays weirdly.

**Comment by eduardot42** [comment]
Seems to have fixed itself, might have been an issue with my machine only.

Also I have a suggestion for keyboard shortcuts for your package, I added these to my personal one, and they work great:

> 'body':
>    'alt-cmd-b': 'sync-settings:backup'
>    'alt-cmd-r': 'sync-settings:restore'
>    'alt-cmd-v': 'sync-settings:view-backup'

**Comment by jerone** [comment]
Maybe a temporary issue with Atom's notifications. Great it's fixed now.

> Also I have a suggestion for keyboard shortcuts for your package...

We [removed](https://github.com/Hackafe/atom-sync-settings/issues/69) the previously added keymaps, so people don't trigger them by accident. As you already found, you can always defined their own keymaps.
