### ISSUE TITLE
Broken in Atom 1.0.9

### ISSUE THREAD

**Issue by gsklee** [Hackafe/atom-sync-settings#122]
`sync-settings` has broken after my Atom was autoupdated from 1.0.7 to 1.0.9. It's not sync'ing my setting changes to Gist anymore.

**Comment by jerone** [comment]
Can you provide some clear steps how to reproduce.
Do you see any errors in the console?
Are you running the latest version?

**Comment by gsklee** [comment]
First things first... does the package automatically sync any change to the settings back to the Gist file?

**Comment by LoLei** [comment]
No it does not, you have to manually back the settings up via `sync-settings:backup` command.

**Comment by gsklee** [comment]
Ooookay, oops.
