### ISSUE TITLE
error when syncing with extra files

### ISSUE THREAD

**Issue by deeperx** [Hackafe/atom-sync-settings#123]
I'm trying to sync my ~/coffeelint.json file (_which is a text format as you guess_) and I'm getting the following error:

```json
{
   "message":"Validation Failed",
   "errors":[
      {
         "resource":"Gist",
         "code":"invalid",
         "field":"files"
      },
      {
         "resource":"Gist",
         "code":"custom",
         "field":"Whoops,",
         "message":"Whoops, files can't contain malformed path components."
      }
   ],
   "documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"
}
```

**I'm suspicious that [this code](https://github.com/Hackafe/atom-sync-settings/blob/a167d7a8f1fddd35039466d311f587a2302c84eb/lib/sync-settings.coffee#L120) is guilty of this.** Because, the error message in Atom's development log trying to send a file to my gist which is not exist: ```/Users/inanc/.atom//Users/inanc/coffeelint.json```. I think that we should add leading slash check there.

-----

**BTW:** I've prevented the error by copying my ```coffeelint.json``` from my ```home folder``` to ```~/.atom``` folder. And, then adding only as ```coffeelint.json``` without: ```~/coffeelint.json``` as it is not recognize that format.

**Comment by jerone** [comment]
All extra files are relative to your `.atom` folder. The correct way is indeed to set `coffeelint.json` as setting.
