### ISSUE TITLE
Feature Request: Blacklist Settings

### ISSUE THREAD

**Issue by deanrather** [Hackafe/atom-sync-settings#126]
For example, I have my wakatime API key in my atom-wakatime settings, I don't want this being synced, any more than I want my gist token being synced (which I noticed is being blacklisted from the config.json)

**Comment by jerone** [comment]
Ref: https://github.com/Hackafe/atom-sync-settings/pull/97#issuecomment-120666519

**Comment by dirk-thomas** [comment]
This is a duplicate of #165 and has been implemented in #177.
