### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by 8427003** [Hackafe/atom-sync-settings#127]
![image](https://cloud.githubusercontent.com/assets/5475231/9909891/f17008f8-5ccc-11e5-93b6-bd49a04b65c7.png)

**Comment by jerone** [comment]
Can you [provide more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues).

**Comment by dirk-thomas** [comment]
Without further information this can not be debugged. Assuming this is not a problem anymore I will close this ticket. If you are still experiencing the problem please comment with more information.
