### ISSUE TITLE
Success message shows escaped HTML

### ISSUE THREAD

**Issue by adambuczynski** [Hackafe/atom-sync-settings#129]
First of, great work on the recent updates, the package is working much smoother now.

Small issue: after syncing to the gist the message that shows up contains escaped HTML:

![ss](https://www.dropbox.com/s/ootyrhtmm2zatl1/Screenshot%202015-09-24%2008.12.17.png?dl=1)

**Comment by jerone** [comment]
Ref: https://github.com/Hackafe/atom-sync-settings/pull/75

I've seen it happen, then it went like it should again, and now it's back :(

Maybe we need to push this upstream, as Markdown (which includes HTML) [is supported by notifications](https://github.com/atom/notifications/blob/master/lib/notification-element.coffee#L84).

**Comment by adambuczynski** [comment]
Yes, sometimes it seems to show up ok, but then another time it's broken again. It might have to do with the notifications system itself.

**Comment by socketubs** [comment]
This bug is still present in `1.4-beta2`.

**Comment by adambuczynski** [comment]
Seems to be fixed now, haven't seen it happening in a while
