### ISSUE TITLE
Uncaught TypeError: cb is not a function

### ISSUE THREAD

**Issue by washit365** [Hackafe/atom-sync-settings#135]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught TypeError: cb is not a function

```
At /Users/nakamuradaisuke/.atom/packages/sync-settings/lib/sync-settings.coffee:193

TypeError: cb is not a function
  at /Users/nakamuradaisuke/.atom/packages/sync-settings/lib/sync-settings.coffee:193:7
  at /Users/nakamuradaisuke/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:342:17
  at callCallback (/Users/nakamuradaisuke/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
  at IncomingMessage.<anonymous> (/Users/nakamuradaisuke/.atom/packages/sync-settings/node_modules/github/index.js:796:25)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:889:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

```

### Commands

```
     -0:13.8.0 sync-settings:check-backup (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:03.4.0 sync-settings:restore (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "_analyticsUserId": "88b54d12-7a61-4d12-b101-9f54565e49db",
    "personalAccessToken": "14535ccfb3f3e05f6a83ba8381ae437ea9ef44d9",
    "gistId": "325226ffbbf2825c9431",
    "_lastBackupHash": "32ca8c9fed3bd9840438cfefe97932421b23602c"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
batman-syntax, v1.0.1
build, v0.47.0
color-picker, v2.0.13
docblockr, v0.7.3
file-icons, v1.6.10
git-projects, v1.15.0
japanese-menu, v1.4.0
linter, v1.8.1
linter-javac, v1.2.0
minimap, v4.13.4
project-manager, v2.6.1
sync-settings, v0.6.0
term2, v0.9.21
vim-mode, v0.61.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by rwcorbett** [comment]
I am also getting this error

**Comment by hexathos** [comment]
Same here during restore of Settings.

**Comment by spcoder** [comment]
Just received the same error on Windows

**Comment by lstep** [comment]
Me too, just restoring a configuration on Linux

**Comment by jeffdavidthompson** [comment]
Joining the club.

**Comment by Waldbillig-Thomas** [comment]
+1, restoring config under linux.

**Comment by knpwrs** [comment]
Same here. I'm probably going to start debugging this soon if nobody else is because I haven't used this package before but I really want it to work.

**Comment by knpwrs** [comment]
Went to start debugging and the sync worked for me... Not sure what was going on there.

**Comment by s2t2** [comment]
I got this error as well after performing a sync on a new device. Not sure if it has anything to do with the fact that I used a different github access token than the one I used on my previous device...

**Comment by dirk-thomas** [comment]
It would be great if someone could try the proposed patch from @knpwrs and comment here if it fixes the problem for them.

**Comment by xggrnx** [comment]
works with patch by @knpwrs t.y.

**Comment by dirk-thomas** [comment]
Also in the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by admdh** [comment]
i had same issue (on MAC OS X) but after enabling Sync Packages it gone and everything synced good.
