### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by curio77** [Hackafe/atom-sync-settings#142]
Despite having set up Atom in such a way that its package retrieval, update etc. mechanisms work behind our corporate proxy, sync-settings always yields a "502 Bad Gateway" error. I suspect that its transport mechanism ignores proxy settings Atom itself respects, hence the error.

This has been so forever and is true for Atom v1.1, sync-settings v0.6.0 in particular.

**Comment by daagar** [comment]
+1

**Comment by mhsu0020** [comment]
Looks like it's due to the node GitHub wrapper not supporting proxy. They never merged the pull request that fixed the problem: 

[https://github.com/mikedeboer/node-github/pull/282](https://github.com/mikedeboer/node-github/pull/282)

**Comment by dirk-thomas** [comment]
The npm package `github` seems to be unmaintained (https://github.com/mikedeboer/node-github/issues/302). Luckily someone stepped up, created a fork, and applied most of the patches (including the one we seem to need for proxy support: https://github.com/kaizensoze/node-github/wiki/Transition-from-upstream).

@jerone Should we (try to) switch our `github` dependency (https://github.com/Hackafe/atom-sync-settings/blob/009e98c572c2048a4822c1b2a580269811be0e2b/package.json#L23) to `github4` (https://github.com/kaizensoze/node-github)?

**Comment by jerone** [comment]
That looks promising. Have you tried github4? Making sure nothing breaks with our calls... It doesn't looks like the original package is getting the correct update soon.

You can always open up an PR here and ask others to test.

**Comment by dirk-thomas** [comment]
I just found `github4` but it seems to pass all tests and a quick check of backup / restore continued to work for me.

@curio77 @daagar @mhsu0020 Can you please try the modified version from PR #167 and comment if it does (or does not) fix your problem with proxies.

**Comment by mhsu0020** [comment]
@dirk-thomas thanks for the fix! Works for me now over http proxy. I did have to set a HTTP_PROXY environment variable on windows for it to work, as github4 grabs the proxy settings from process.env

**Comment by dirk-thomas** [comment]
Thank you for confirming that it works for you. I will close this with #167 being merged.

**Comment by Hankszhang** [comment]
With the newest Atom & sync-settings, I still can't use behind corporate proxy

**Comment by dirk-thomas** [comment]
@Hankszhang it might help if you mention how you have configured your proxy for others to comment if they did it differently.

**Comment by Hankszhang** [comment]
@dirk-thomas I set proxy(http://proxy-url:8080) both for apm and git, but it didn't work.

**Comment by dirk-thomas** [comment]
I don't use a proxy so I can't help you with this topic. You might either find some information in #26 or someone will comment with additional ideas.

**Comment by mhsu0020** [comment]
@Hankszhang in addition to .apmrc  settinga, you need to set the http_proxy and https_proxy environment variables, since it is pulling from process.env

**Comment by Hankszhang** [comment]
@mhsu0020 May I ask how to set the http_proxy and https_proxy environment variables

**Comment by mhsu0020** [comment]
@Hankszhang `export http_proxy=http://proxy-url:8080` and `export https_proxy=http://proxy-url:8080`. If on windows, use `set` instead of `export`

**Comment by Hankszhang** [comment]
@mhsu0020  Thx, but this way still didn't work for me... Finally i tried this way which @zww-v5 metioned in  #273 ,it work for me

**Comment by eltian** [comment]
I can't make it work. Is there a way to specify user/pass for the proxy? In my case, the error says "Cache access denied"

**Comment by sebdelvalle** [comment]
As far as I can see, you can't (still) use sync-settings with a corporate proxy, even despite atom can, right?

**Comment by eltian** [comment]
As a matter of fact, I managed to make it work by adding user, password and port to the proxy url, following @zww-v5 solution in #273.

The syntax I'm using is:
`proxy: 'http://[user]:[password]@proxy.cooperativaobrera.coop:[port]'`

That should cover most cases.
