### ISSUE TITLE
Detect local changes, suggest backup

### ISSUE THREAD

**Issue by borekb** [Hackafe/atom-sync-settings#143]
I sometimes forget to manually back up local changes which can be frustrating. I'm the stupid here, I know, but it would be nice if changes were detected automatically and backup was suggested. (This could even be done automatically but I guess that should be configurable as not everybody will want to sync settings all the time.)

**Comment by dbkaplun** [comment]
+1 it doesn't even have to watch for changes, it can simply compare the old backup against a new backup every 24 hours. Shouldn't take more than a few lines of code.

**Comment by dirk-thomas** [comment]
Very similar to #27. Therefore I will close this as a duplicate.
