### ISSUE TITLE
Uncaught Error: OAuth2 authentication requires a token or key 

### ISSUE THREAD

**Issue by puxoskii** [Hackafe/atom-sync-settings#148]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by dirk-thomas** [comment]
Duplicate of #147. Closing.
