### ISSUE TITLE
Bad credentails

### ISSUE THREAD

**Issue by kolombet** [Hackafe/atom-sync-settings#153]
Copied token and gist id to settings. token have access to gist. Can't upload. Sync error it says. Bad credentails.

Only View backup works, but there no backup, my empty gist.

**Comment by AbrahamAlcaina** [comment]
I have the same issue

**Comment by socketubs** [comment]
I encounter this issue but it was pretty simple. I just copy paste my personnal api key and my settings look like that: 
![screenshot from 2015-12-23 23-41-34](https://cloud.githubusercontent.com/assets/293337/11986359/eaaee698-a9ce-11e5-9986-bafde2d3a938.png)

There were a new line that have been catch and produce a "Bad credentials" error.
Maybe  `atom-sync-settings` must trim settings value ?

**Comment by dirk-thomas** [comment]
@kolombet @AbrahamAlcaina Can you confirm that the reason for your problem was the same as for @socketubs? If not, did you find out what the problem was in your case?

**Comment by kolombet** [comment]
I had few spaces at the end of access token. That were the reason of error.

**Comment by socketubs** [comment]
As api key doesn't have spaces, it could be a easy to strip them to avoid bad copy paste that add spaces.

**Comment by dirk-thomas** [comment]
I created PR #178 which will trim the Gist ID as well as the personal access token.
