### ISSUE TITLE
Enhancement proposal: allow customizing gist's description

### ISSUE THREAD

**Issue by krzysztof-sikorski** [Hackafe/atom-sync-settings#163]
It would be nice if user could customize the description of a gist used by this package.
Right now it's just `automatic update by http://atom.io/packages/sync-settings`.

**Use case:** I use two different sets of configuration (work *vs* home/hobby), which lead to two different gists used to backup the settings. Right now both gists look the same on Gist website, they can be distinguished only by looking at file contents or by checking history and trying to remember when each config was synced.

**Comment by dirk-thomas** [comment]
I implemented this feature in #171. It would be great it if you could try the patch and comment if it works the way you imagined.

**Comment by krzysztof-sikorski** [comment]
Yes, the patch works great.

Screenshot attached, the top Gist was updated by a patched package, the second one by unpatched package.

![screenshot](https://cloud.githubusercontent.com/assets/4456257/12390052/387385ba-bddd-11e5-86b5-2365d3208b7c.png)

**Comment by dirk-thomas** [comment]
Thank you for checking!
