### ISSUE TITLE
Uncaught Error: OAuth2 authentication requires a token or key 

### ISSUE THREAD

**Issue by crunchex** [Hackafe/atom-sync-settings#184]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by jerone** [comment]
As the error message states _"...authentication requires a token..."_, you need to [add a valid Gist Id and Personal Access Token to the settings](https://github.com/Hackafe/atom-sync-settings#setup).
