### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jerone** [Hackafe/atom-sync-settings#19]
Bug report from Atom:

> atom.workspaceView is no longer available.
> In most cases you will not need the view. See the Workspace docs for
> alternatives: https://atom.io/docs/api/latest/Workspace.
> If you do need the view, please use `atom.views.getView(atom.workspace)`,
> which returns an HTMLElement.
> ```
> Atom.Object.defineProperty.get (c:\Users\jerone\AppData\Local\atom\app-0.174.0\resources\app\src\atom.js:55:11)
> Object.activate (c:\Users\jerone\.atom\packages\sync-settings\lib\sync-settings.coffee:20:9)
> ```

**Comment by RossBarnie** [comment]
I've got a pull request on the way for this.
