### ISSUE TITLE
Warning that gists are public by default

### ISSUE THREAD

**Issue by BenSower** [Hackafe/atom-sync-settings#190]
Heyho,

by now, atom features a lot of different api-plugins (e.g. slack-chat), often using access-tokens, which are also synced by sync-settings. If gist is not explicitly set to "secure" the tokens can be found and eventually abused by anyone searching for "atomsync".
I found at least one person with an exposed token on github.

I am proposing to add something along the lines of "Create a secure gist, if your sync-settings should not be publicly indexed." to the fourth step in the usage instructions.

**Comment by dirk-thomas** [comment]
Can you please create a pull request with you suggested improvements to the readme.

**Comment by BenSower** [comment]
No Problem: https://github.com/Hackafe/atom-sync-settings/pull/191

**Comment by dirk-thomas** [comment]
Thanks.
