### ISSUE TITLE
No feedback about errors

### ISSUE THREAD

**Issue by mik01aj** [Hackafe/atom-sync-settings#21]
I just installed the plugin, I generated a key, created a secret gist, then I press "upload settings" in menu and nothing happens. I press Ctrl+alt+u and nothing happens. Even the console is empty.

And when I go to the gist page, it's empty as I left it.

I suppose that some error happened on the way, but I would certainly appreciate some message about this in the UI.

**Comment by mik01aj** [comment]
Hi, it looks like the settings were uploaded after a few minutes, but still, some visual feedback about the whole operation would be great. When you don't give visual feedback, users will think your application is broken, even when it isn't.

**Comment by kalkov** [comment]
@mik01aj : Thanks, good idea

**Comment by jerone** [comment]
Notification where [added](https://github.com/Hackafe/atom-sync-settings/pull/17) just before this issue.

You can open another issue if you want more specific notifications.
