### ISSUE TITLE
Synchronize custom files too

### ISSUE THREAD

**Issue by Trudko** [Hackafe/atom-sync-settings#22]
Hi, right now it is only possible to synchronize predefined list of files. How about to let user to synchronize other files too? For example I use Project Manager which stores settings for project in project.cson and I would like to synchronize it too.

I am happy to add this, just want to know if you would be interested.

**Comment by philipgiuliani** [comment]
Really cool idea :) I could also use this! :+1:
Shouldn't be that hard :)

**Comment by plttn** [comment]
Honestly, I'd disagree on syncing that kind of stuff.

They vary by environment. On one client, the path to a project might be `C:/Github/foobar`, and on another it is `~\Github\foobar`.

Syncing them would continually break your project folders.

**Comment by Trudko** [comment]
Project manager was just an example there are other packages which uses extra files. plus if you have consistent environment that shouldn't be a problem. I have projects on the same path on both machines.

**Comment by plttn** [comment]
Right but the point is making that assumption is probably not the best idea.

**Comment by RossBarnie** [comment]
Well that's why we don't use OS-specific paths. Personally, I don't see a problem with this as long since the default behaviour would be untouched and if people want to sync more things they can.

**Comment by jerone** [comment]
This has been implemented by https://github.com/Hackafe/atom-sync-settings/pull/32
