### ISSUE TITLE
Not working on 0.181.0

### ISSUE THREAD

**Issue by williamboman** [Hackafe/atom-sync-settings#28]
First of all, the selectors are deprecated, so I had to add my own with `atom-workspace` selector.

Secondly, nothing happens when I trigger the download event? The keybinding resolver says it resolves to `sync-settings:download` properly, but nothing happens after that?

`atom 0.181.0` `sync-settings 0.2.1`

**Comment by williamboman** [comment]
After restarting Atom x times it successfully downloaded it. The console does not log anything when triggering the `sync-settings:download` event when it's unsuccessful (i.e. nothing happens).

Regarding the selector issue, I'm a bit confused here - the workspace selector has never been `.atom-workspace`, it's been `.workspace` or `atom-workspace`, correct me if I'm wrong?

**Comment by RossBarnie** [comment]
I'm not getting any deprecation issues are you sure you aren't using your own dev build? #20 solved the deprecated selectors. I'm also not having any issues with 0.181.0 atom with this package.

**Comment by williamboman** [comment]
This is so weird.. After removing my custom keybindings, it started working as expected until I restarted the editor. Then it stopped working until I re-added my custom keybindings - this worked until I restarted the editor again. This goes on forever.

**Keybinding resolver**
*With custom keybinding*
![](http://i.imgur.com/W21cuGr.png)

*Without*
![](http://i.imgur.com/9uoN63s.png)

The console is empty when it doesn't work.

**Comment by RossBarnie** [comment]
I'm having some inconsistencies as well. A moment ago the sync settings commands weren't showing in  the command palette, but now they are. I'll see if there's any kind of pattern to this if it happens again...

**Comment by groupsky** [comment]
In the code there are several console.log/debug especially for upload/download. Although I haven't checked with latest atom ide, they should show in the dev console.

**Comment by williamboman** [comment]
Closed in #30
