### ISSUE TITLE
Hight startup time

### ISSUE THREAD

**Issue by Trudko** [Hackafe/atom-sync-settings#33]
Compared to other package sync settings is taking (according to timecop) by far the most time 440ms for package loading. Don't have time right not to check the code for what might be the problem, but I am happy to help with it.

**Comment by groupsky** [comment]
Thanks for the report @Trudko. This is strange, since the plugin doesn't do any particular operations on startup.

**Comment by Trudko** [comment]
So if used timecop, did you get similar results?

**Comment by groupsky** [comment]
Just tested on 0.177.0 - timecop gives 12ms for sync-settings. I remember seeing some high values during development of the plugin, but never investigated.

**Comment by olmokramer** [comment]
I'm getting `10ms` for package loading, and it's not in the list of package activation, so `< 5ms`

**Comment by Trudko** [comment]
Hmm , I tried it again by opening Atom and running Time cop and the results:

![sync-settings](https://cloud.githubusercontent.com/assets/3289225/6521917/f7bad220-c3dd-11e4-9008-03d51223e373.png)

I will test it on different PC and different OS , could be interesting to look at :)

**Comment by groupsky** [comment]
I made some tests and here is the result:

* source package (symlink) w/i node_modules - **260ms**
* source package (symlink) w/o node_modules - **130ms**
* published package - **10ms**

Haven't tried with other packages, to confirm it happens when you use the sources, rather than installed from packages.

**Comment by groupsky** [comment]
@Trudko can you check the latest commit f089f28. Maybe it will provide better loading time.

**Comment by jerone** [comment]
Just came here to report the same issue. I have 88 packages installed and Sync Settings takes more then 1/4 of the total package loading time (284 from 1091ms).

Atom 0.192.0
Sync Setting 0.2.2
Windows 7 64-bits

**Comment by ypresto** [comment]
Same issue.

sync-settings: 316ms
coffee-refactor: 90ms
vim-mode: 49ms

**Comment by jerone** [comment]
It might be an suggestion to lazy load some dependencies.

**Comment by ypresto** [comment]
![2015-04-26 10 07 06](https://cloud.githubusercontent.com/assets/400558/7335451/76ff881e-ebfc-11e4-8f29-15bad21ef506.png)

[this line in q.js](https://github.com/kriskowal/q/blob/v1.0.1/q.js#L68) builds stack trace, as Error.prepareStackTrace will be called at `new Error()` (https://code.google.com/p/v8-wiki/wiki/JavaScriptStackTraceApi).

Error.prepareStackTrace is set by CoffeeScript, and it seems to try to load source map.
Strangely even q.js is plain JavaScript file...

**Comment by ypresto** [comment]
Investigated on prepareStackTrace with debugger, and I found I was wrong about plain js file.
js files do not cause source map loading, but coffee files in stack such as sync-settings.coffee cause it.

prepareStackTrace is called on but below line, not `new Error()`.

```
    hasStacks = !!e.stack;
```

**Comment by jerone** [comment]
Fixed by https://github.com/Hackafe/atom-sync-settings/pull/48
