### ISSUE TITLE
Snippets not getting applied

### ISSUE THREAD

**Issue by elebetsamer** [Hackafe/atom-sync-settings#36]
I've created a new snippet in my snippets.cson file and then did an sync-upload. I can see the file in my gist and it has my snippet. I move to my other machine, do a sync-download and my snippets.cson file remains unchanged.

**Comment by RossBarnie** [comment]
What OS are you using? Have other files synced properly?

**Comment by elebetsamer** [comment]
I tried it on my mac and on windows. I'm using Atom 0.188.0 on windows 8.1 and OSX 10.10.2 It seems like all files are syncing other than the snippets.

**Comment by Gr1mdrag0n** [comment]
I'm experiencing the same issue.  Created snippets and uploaded on a Win7 machine (atom 0.190.0), tried downloading on a Win8 machine (atom 0.190.0) and the snippets didn't download.  Both machines can properly upload snippets.  The download did update the them though.

**Comment by almostearthling** [comment]
There's a reference to `snippets.coffee` when writing to the gist, which actually is not the needed file. I created a branch for the solution.

F.
