### ISSUE TITLE
Fix travis build of pull request

### ISSUE THREAD

**Issue by groupsky** [Hackafe/atom-sync-settings#40]
The problem is with the oauth token for github. GitHub doesn't allow the token to be commited in the repo, but it is specified as a secure var in travis config. But unfortunately when travis builds it doesn't get the actual token, but an old one.

When building normal commits, the token is correct.

**Comment by jerone** [comment]
All Travis CI builds fail because of this. Please fix.

**Comment by jerone** [comment]
So after some investigating I found out the following:
* Our `GITHUB_TOKEN` variable is encrypted as [secret](http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables).
* For security reason Travis CI [doesn't use the secret variables in PR](http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests).
* I can add environment variables [through their UI](http://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings): `Settings` > `Environment Variables`.
* The manual added variables can be hidden from the logs by the setting: "Display value in build logs".
* After [testing](https://travis-ci.org/jerone/atom-sync-settings/builds/66126686) I found out that PR's do accept the manual variables (a PR from my fork).

@groupsky Can you provide me the unencrypted `GITHUB_TOKEN` or [manually set](http://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) the variable through the Travis CI UI?

**Comment by groupsky** [comment]
@jerone I changed to set it through the UI but seems the hidden value is equivalent to encrypted one and thus not working for PRs. Anyway the token is for a dedicated test account, so i'm not worried about leaking the token.

**Comment by groupsky** [comment]
It seems new PRs are now working - tested with one of mine, but I can't get the existing to pass even though the logs show they are using the correct token. Maybe the PR is actually broken?

**Comment by jerone** [comment]
Apparently the setting _"Display value in build logs"_ was **off**, which made it a secure setting again, failing for PR's again. I put it to **on** and all is well now.

**Comment by groupsky** [comment]
I think the changes [broke the specs](https://travis-ci.org/Hackafe/atom-sync-settings/builds/66184328#L133). Maybe the specs should pre-call activate?
