### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getUserKeymapPath' of undefined

### ISSUE THREAD

**Issue by pfefferle** [Hackafe/atom-sync-settings#43]
[Enter steps to reproduce below:]

1. Installed plugin on a second machine
2. Added access token and gist ID
3. ran sync-download

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getUserKeymapPath' of undefined

```
At /Users/matthias/.atom/packages/sync-settings/lib/sync-settings.coffee:96

TypeError: Cannot read property 'getUserKeymapPath' of undefined
  at /Users/matthias/.atom/packages/sync-settings/lib/sync-settings.coffee:96:41
  at /Users/matthias/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:342:17
  at callCallback (/Users/matthias/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
  at IncomingMessage.<anonymous> (/Users/matthias/.atom/packages/sync-settings/node_modules/github/index.js:796:25)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
  2x -0:51.3.0 sync-settings:download (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "sync-settings": {
    "personalAccessToken": "7c2b6afbe68ea7b10ee17819db0e41cbcc7d04fa",
    "gistId": "577155c3ef97b89b810d"
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.2.2

# Dev
No dev packages
```

**Comment by pfefferle** [comment]
After restarting Atom from the bash, it seems to work... Sorry...

**Comment by AdamBuczynski** [comment]
I am experiencing the same issue, but restarting Atom doesn't help here.

**Comment by dapitts08** [comment]
I am experiencing the same issue, but restarting Atom does not solve mine either.

**Comment by AdamBuczynski** [comment]
I've actually experienced this and some other errors every time I try to download my settings, and a lot of times "undefined" will appear in the files instead of the content from the GIST.

It seems syncing is still a bit unstable.

**Comment by ypresto** [comment]
In Atom 0.206.0 this always reproduces but `--include-deprecated-apis` option for atom command.

**Comment by ypresto** [comment]
@groupsky Is repo still maintained?

**Comment by jerone** [comment]
[**@ypresto**](https://github.com/ypresto) commented on [5 jun. 2015 04:39 CEST](https://github.com/Hackafe/atom-sync-settings/issues/43#issuecomment-109141454 "2015-06-05T02:39:40Z - Replied by Github Comment Enhancer"):
> [@groupsky](https://github.com/groupsky) Is repo still maintained?

It doesn't look like it. In a week I have some spare time to fork this repo with a [few fixes](https://github.com/Hackafe/atom-sync-settings/pulls) I have lined up. Still hoping someone from @Hackafe steps up!

**Comment by groupsky** [comment]
I haven't been using atom lately and if anyone wants to step in as a
maintainer, I'm happy to step down. Meanwhile I'm getting back from
vacation tomorrow so I'll check the PRs before Monday.

**Comment by jerone** [comment]
[**@groupsky**](https://github.com/groupsky) commented on [5 jun. 2015 21:38 CEST](https://github.com/Hackafe/atom-sync-settings/issues/43#issuecomment-109415952 "2015-06-05T19:38:51Z - Replied by Github Comment Enhancer"):
> I haven't been using atom lately and if anyone wants to step in as a
> maintainer, I'm happy to step down. Meanwhile I'm getting back from
> vacation tomorrow so I'll check the PRs before Monday.

I'm interested in getting this package updated and working again.

**Comment by almostearthling** [comment]
@jerone There are at least two options: either you (or someone else) become a maintainer of the project, or someone starts to maintain a fork as a separate and backward-compatible package. The second option can also be interesting, for instance in order to add capabilities - such as the possibility to use a shared folder instead of a gist for a repo, thus allowing dropbox-like applications to do the sync job.

I'd propose myself too, if only I managed to get into coffeescript enough. But I still didn't have the chance, and it would be quite pretentious as a newbie!

F.

**Comment by jerone** [comment]
Like I said I have some time in a few days to look at this. I'm hoping this can be part of this repo with it's current users taking advantage of it. Because forking and renaming to create another package doesn't sound like a good solution with existing users (3500+).

My suggestion is to move this repo to a new team called "atom-sync-settings-community" (or something). That way I and others can join this repo without being linked to the @hackafe group, which I don't have any 'affiliation' with.

**Comment by almostearthling** [comment]
Fair enough. Also, another name wouldn't be as self-explanatory.

F.

**Comment by jerone** [comment]
@groupsky Anyway to contact you, or you contact me (mail, Slack, gitter)?

**Comment by jerone** [comment]
Fixed in https://github.com/Hackafe/atom-sync-settings/commit/292b1654477341bdd344465dfee135bba3a516ee

**Comment by dirk-thomas** [comment]
@pfefferle In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.
