### ISSUE TITLE
Extra files contents undefined

### ISSUE THREAD

**Issue by jerone** [Hackafe/atom-sync-settings#44]
Today I tried uploading my settings with extra files defined. Aldo the files were created, the contents was `undefined`.

**Comment by varemenos** [comment]
This really needs to be fixed, I've lost quite a few configuration files due to it saving them undefined...

**Comment by cyanpunk** [comment]
This is still present. Just lost some of configuration settings due this bug. :(

**Comment by jerone** [comment]
This is the first one on my roadmap!

**Comment by jerone** [comment]
@varemenos @cyanpunk @kankaristo Just pushed a new version with the fix for this included :tada:

**Comment by kankaristo** [comment]
Yay, thanks! :+1:

**Comment by cyanpunk** [comment]
Thanks mate! :+1:

**Comment by varemenos** [comment]
:clap: :clap: :clap:
