### ISSUE TITLE
Settings.json created

### ISSUE THREAD

**Issue by AdamBuczynski** [Hackafe/atom-sync-settings#49]
I have my configuration in config.cson, but due to an old install I had, the first sync I did included a settings.json file as well. I've since removed settings.json from both my machines and from the gist, but for some reason it re-appears every time I save my settings to the gist. Is this intentional for some reason?

**Comment by xeor** [comment]
I was wondering the same thing..

Looks like atom is using `config.cson` for its storage, but `atom-sync` names it `settings.json` when stored. Look at the upload function at https://github.com/Hackafe/atom-sync-settings/blob/master/lib/sync-settings.coffee#L38. `atom.config.settings` is an object with all the settings, not a reference to a file. This is a good thing I guess, as atom-sync doesnt haveto worry about where the settings are coming from, but gets it directly from atom's api.

**Comment by jerone** [comment]
@xeor is correct. All settings are fetched from the `atom.config.settings` object and then stored in your gist with the (not same name) `settings.json`. When downloaded all settings from your `settings.json` are read and [stored again in the `atom.config.settings` object](https://github.com/Hackafe/atom-sync-settings/blob/master/lib/sync-settings.coffee#L90). Everything works as expected, except for the same name convention.

**Comment by AdamBuczynski** [comment]
But does atom-sync then also maintain the config file `config.cson`? Because that one does end up in my gist as well. Will this conflict with applying the settings directly to atom?

**Comment by jerone** [comment]
`config.cson` shouldn't standard be synced. There's no code that fetches that file. Did you define it as "Extra Files"?

**Comment by AdamBuczynski** [comment]
No I didn't. I think maybe I added it manually to the gist.

I tried uploading my settings again and can see the `settings.json` being created, but it's missing some settings which are found in `config.cson`. Most notably the settings from package sync-settings itself. Is this intentional?

**Comment by xeor** [comment]
Yes.. `sync-settings` are removed (see https://github.com/Hackafe/atom-sync-settings/blob/master/lib/sync-settings.coffee#L10, and its usage in the `filterSettings` function down the same file. That is removed because it was a security risk since not everyone had paid github accounts, and had public gist's.. See https://github.com/Hackafe/atom-sync-settings/issues/14

**Comment by AdamBuczynski** [comment]
Ok, thanks for clarifying.

**Comment by jerone** [comment]
So the name differences (`settings.json` vs `config.cson`) probably makes sense then.
