### ISSUE TITLE
uploading from a Mac and download to Linux

### ISSUE THREAD

**Issue by wllmcdl** [Hackafe/atom-sync-settings#52]
The idea is awesome but it should have some settings, like what do we want to upload (just package settings, just keymap or just package configuration) because I did an upload from a mac to download in linux and it got messy.

**Comment by timfallmk** [comment]
@wllmcdl What exactly got messy? I use this to regularly sync between Linux and Mac and the only issue I've found is #54

**Comment by wllmcdl** [comment]
After i downloaded on linux something went wrong I thought it messed something but was another package...
