### ISSUE TITLE
Atom 0.206.0 - Uncaught TypeError: Cannot read property 'getUserKeymapPath' of undefined

### ISSUE THREAD

**Issue by diogosg** [Hackafe/atom-sync-settings#55]
After upgrade Atom for version 0.206.0, the Atom Sync Settings v0.2.2 crashed.

**Error:**
TypeError: Cannot read property 'getUserKeymapPath' of undefined
    at /home/user/.atom/packages/sync-settings/lib/sync-settings.coffee:153:45
    at /home/user/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:342:17
    at callCallback (/home/user/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
    at IncomingMessage.<anonymous> (/home/user/.atom/packages/sync-settings/node_modules/github/index.js:796:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)

**Comment by jerone** [comment]
Confirmed on Atom 0.207.0

**Comment by varemenos** [comment]
I can confirm this at 0.206.0

**Comment by jesperronn** [comment]
I can confirm it too (on 0.207). Any ideas on how to fix it? Pull-requests, anyone?

**Comment by dustinblackman** [comment]
Fix. https://github.com/Hackafe/atom-sync-settings/pull/56

**Comment by djindjic** [comment]
:+1:

**Comment by williamboman** [comment]
Confirmed on `0.207.0`

**Comment by jerone** [comment]
Fixed in https://github.com/Hackafe/atom-sync-settings/commit/292b1654477341bdd344465dfee135bba3a516ee

**Comment by williamboman** [comment]
@jerone Tag new release :)?

**Comment by jerone** [comment]
[**@williamboman**](https://github.com/williamboman) commented on [8 jun. 2015 17:37 CEST](https://github.com/Hackafe/atom-sync-settings/issues/55#issuecomment-110046815 "2015-06-08T15:37:08Z - Replied by Github Comment Enhancer"):
> @jerone Tag new release :)?

Hopefully tonight. Hang on :relaxed:

**Comment by williamboman** [comment]
:+1:, thanks!

**Comment by djindjic** [comment]
thanks

**Comment by dustinblackman** [comment]
Cool cool, thanks for accepting PR.

**Comment by 1ternal** [comment]
same issue, Atom v 0.207.0

**Comment by cyanpunk** [comment]
When the update will be available?

**Comment by jerone** [comment]
I'm having issues getting Travis CI to work. When that's fixed I can test and release a new version. Excuses that it's taking so long.
