### ISSUE TITLE
Uncaught Error: OAuth2 authentication requires a token or key 

### ISSUE THREAD

**Issue by touyou** [Hackafe/atom-sync-settings#60]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.3.0

### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by jerone** [comment]
As the error message states "...authentication requires a token...", did you [added a valid Gist Id and Personal Access Token to the settings](https://github.com/Hackafe/atom-sync-settings#usage)?

**Comment by yoshokatana** [comment]
I'm also getting this error, when trying to download an already-uploaded settings gist on a new computer.

Steps to repro:

1. `rm -rf ~/.atom`
2. install fresh osx atom version
3. `apm install sync-settings`
4. add token + gist ID (same as the ones used when uploading) to `~/.atom/config.cson`
5. try to run the download (or press ctrl + alt + D)
6. That error pops up.

**Comment by jerone** [comment]
[**@yoshokatana**](https://github.com/yoshokatana) commented on [14 jun. 2015 20:08 CEST](https://github.com/Hackafe/atom-sync-settings/issues/60#issuecomment-111859598 "2015-06-14T18:08:28Z - Replied by Github Comment Enhancer"):
> EDIT:  Just figured it out! `"sync-settings"` needs to be under the `"*"` object in the `config.cson`, rather than at root level. It wasn't seeing the config.

The best thing to do is use the package Settings page. Great that you figured it out.
