### ISSUE TITLE
Clean up after #36

### ISSUE THREAD

**Issue by jerone** [Hackafe/atom-sync-settings#68]
I want to discuss if we need to clean up after https://github.com/Hackafe/atom-sync-settings/pull/66 was merged to fix long standing bug #36. The leftover part is a file called `snippets.coffee` which was added when running version 0.4.0 and earlier. The file is completely useless.

We can do a few things:

1. Ignore the issue, the file isn't harmless and people can remove it whenever they want.
2. Do nothing, only mention it in the readme and give instructions how to remove it.
3. Build some logic to remove the file in (only) the next version.

The last solution seems the more friendly solution, solving the problem without any user action. Problem is that there's no API to know when the package is updated from a older version. I propose the following (untested) draft:
```coffeescript
activate: ->
  currentVersion = atom.packages.getLoadedPackage('sync-settings').metadata.version
  if atom.config.get('sync-settings.version') isnt currentVersion 
    fs.unlink(path.join(atom.getConfigDirPath(), 'snippets.coffee'))
    atom.config.set('sync-settings.version', currentVersion)
```

/cc @groupsky

**Comment by jerone** [comment]
So, after some tests, option 3 will add an extra setting in the config. Which is intended so the code doesn't run again, but what I didn't know was that it [also added that setting](https://atomio.slack.com/archives/packages/p1434303024000553) to the package Settings page. The setting isn't intended for people to change and isn't very descriptive which will probably raise questions what it is.

Thinking about it a bit more, `activate` is only run once the user manually specifies to backup or restore (because of `activationCommands`). That give no overhead on Atom start-up and little to non overhead while running. It only runs once for every Atom instance, which is fine if we build a fail-save in when the file isn't there or removed from a previous run.

Hoping this makes sense for others :)

**Comment by jerone** [comment]
Proposed solution here: https://github.com/Hackafe/atom-sync-settings/pull/71

**Comment by groupsky** [comment]
it's dangerous when deleting files, since it may be a real file from another plugin.

**Comment by jerone** [comment]
[**@groupsky**](https://github.com/groupsky) commented on [15 jun. 2015 09:12 CEST](https://github.com/Hackafe/atom-sync-settings/issues/68#issuecomment-111962045 "2015-06-15T07:12:16Z - Replied by Github Comment Enhancer"):
> it's dangerous when deleting files, since it may be a real file from another plugin.

Then the contents of this file would have overridden on every restore/download. I don't think this is an issue.

**Comment by groupsky** [comment]
I think it's safer without touching anything. The lifespan of the bug was only couple of days, but the proposed #71 could stay for quite some time and possibly do more damage in the long run. The scenario I'm mostly worried is if user has a plugin that uses `snippets.coffee` and then installs the **sync-settings**

**Comment by jerone** [comment]
Wouldn't that produce all kind of error messages where the Coffee file was replaced with CSON data from the `snippets.cson` file...

Anyways, the bug was introduced since march: https://github.com/Hackafe/atom-sync-settings/commit/9f5028de286d2c88b9934ab75575d342aef9715f

**Comment by jerone** [comment]
Do you think a message on the readme will be sufficient?

**Comment by groupsky** [comment]
IMHO readme message is the safest bet. Haven't seen any reports about broken `snippets.coffee`, only the #36 regarding not applying the changes. It's just to wild area and we can't be sure if the `snippets.coffee` file is really from **sync-settings** or come from somewhere else.

**Comment by jerone** [comment]
Maybe a message in the changelog...

**Comment by groupsky** [comment]
sounds good
