### ISSUE TITLE
Remove keymaps

### ISSUE THREAD

**Issue by jerone** [Hackafe/atom-sync-settings#69]
Remove both keymaps (<kbd>Ctrl+Alt+U</kbd> and <kbd>Ctrl+Alt+D</kbd>) so people don't trigger by accident and the keymaps clutter Atom with commands that are triggered once in a while. 

As alternative, people can:
* use the Sync Settings menuitems in the Package menu.
* the commands:
  * `sync-settings:backup`
  * `sync-settings:restore`
* make their own keymaps:
  <pre><code>
  'atom-workspace':
    'ctrl-alt-u': 'sync-settings:backup'
    'ctrl-alt-d': 'sync-settings:restore'
  </code></pre>

**Comment by almostearthling** [comment]
Good idea, IMO. :+1: 

F.

**Comment by groupsky** [comment]
sounds ok, to be honest they are left from the early days of development when I needed to run it quite often.

:+1:
