### ISSUE TITLE
Uncaught Error: OAuth2 authentication requires a token or key 

### ISSUE THREAD

**Issue by varemenos** [Hackafe/atom-sync-settings#72]
1. Try to download latest copy of my settings
2. Didn't have the proper token/key for it
3. boom

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.2
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.4.0

### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by jerone** [comment]
You mention "Didn't have the proper token/key for it", does that mean you haven't filled in your token or key?

**Comment by jerone** [comment]
Possible duplicate: https://github.com/Hackafe/atom-sync-settings/issues/60
