### ISSUE TITLE
Check for updated backup

### ISSUE THREAD

**Issue by groupsky** [Hackafe/atom-sync-settings#81]
If we store the last restored/created backup, we can then check on start if there is a newer backup and either restore it automatically or notify user about that. The git commit id should be enough to verify the backup.

**Comment by varemenos** [comment]
:+1:

**Comment by varemenos** [comment]
@jerone man you are on fire, thank you a lot!

**Comment by jerone** [comment]
All credits go to @groupsky :green_heart: I'm just a second pair of eyes.
