### ISSUE TITLE
Track usage

### ISSUE THREAD

**Issue by groupsky** [Hackafe/atom-sync-settings#82]
Some form of analytics (like google analytics provides for websites) to track usage and version distributions would be helpful. Not sure how the privacy should be approached - maybe a opt-on/opt-out setting.

**Comment by jerone** [comment]
I've seen this in other packages too and would like to have it. Do you know what needs to be done to get this implemented?

**Comment by groupsky** [comment]
I can examine the other packages. Can you point to some where you saw that?

**Comment by jerone** [comment]
Open up your `config.cson` and look for the `_analyticsUserId` property.

* [atom-beautify](https://atom.io/packages/atom-beautify)
* [preview](https://atom.io/packages/preview)

**Comment by jerone** [comment]
Interesting: https://github.com/atom/metrics

**Comment by groupsky** [comment]
It seems that both packages (atom-beautify and preview) are using `analytics-node` which is backed by [Segment](https://segment.com/pricing) to report data to Google Analytics. 

The actual code to track and report is pretty strightforward:
* [atom-beautify](https://github.com/Glavin001/atom-beautify/search?utf8=%E2%9C%93&q=analytics)
* [preview](https://github.com/Glavin001/atom-preview/search?utf8=%E2%9C%93&q=analytics)

**Comment by jerone** [comment]
So I thought I give this a try: https://github.com/jerone/atom-sync-settings/tree/features/tracking

I've installed analytics-node (`npm install --save analytics-node`) and setup an account on [Segment](https://segment.com/jerone/sync-settings) with GA activated.

I'm seeing some data in Segment: 
![2015-06-27 16_52_34-tracking plan - segment](https://cloud.githubusercontent.com/assets/55841/8392512/bcc83478-1ced-11e5-875d-623726af792d.png)

But I'm struggling to get this visible in GA, my knowledge about GA is too limited I noticed.

**Comment by groupsky** [comment]
I managed to see it in GA just by replacing the segments key with my own. In GA you usually see the stats from previous month excluding the current day. In live view you can see for events from the tracking. One thing to note - I had to use the long write key, instead of the short api key (the latter says is for enterprise users - no idea what that is).

A working example with some additional features can be seen at [my branch](https://github.com/groupsky/atom-sync-settings/tree/features/tracking)

**Comment by jerone** [comment]
Scanned trough your code; your are not using Segment anymore?

**Comment by groupsky** [comment]
I'm using it, just extracted the tracking into separate class.
