### ISSUE TITLE
Package ordering issue

### ISSUE THREAD

**Issue by jerone** [Hackafe/atom-sync-settings#83]
Backing up from **dev mode** creates a different `package.json` list then in normal mode. The dev packages (`apm links`) are prepended. This results in unneeded revisions.

**Comment by dirk-thomas** [comment]
PR #149 orders the list of packages alphabetically. Is that sufficient for your use case or do you imagine dev packages to be treated differently?

**Comment by jerone** [comment]
Ordering all packages (including the dev packages) solves this issue. Thanks.

Fixed by https://github.com/Hackafe/atom-sync-settings/pull/149
