### ISSUE TITLE
Custom keybinding settings for packages didn't sync

### ISSUE THREAD

**Issue by ryanaltvater** [Hackafe/atom-sync-settings#90]
I just set up Atom on my work machine, and noticed that I had to re-setup custom keybindings for certain packages because they did not carry over from my personal machine in the backup. Is this a bug? Is it a possibility?

**Comment by jerone** [comment]
Do you mean your keymaps from `keymap.cson`?

**Comment by ryanaltvater** [comment]
No, but I think I'm going to move my custom key settings for a specific package to that file which does sync. "Project Ring" allows you to "Edit Keybindings" directly in the package. It makes more sense to not put them in there, but in the keymap.cson. Sorry.

**Comment by jerone** [comment]
Great that you figured it out yourself. We don't backup the whole package folder, sync-settings just downloads a package.
